version: '3.8'

services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  bot:
    build: .
    env_file:
      - .env
    depends_on:
      - redis

volumes:
  redis_data: